from sqlalchemy import Column, Integer, String, Float, DateTime
from .database import Base


class OrderItem(Base): 
    __tablename__ = "items"  

    ordernumber = Column(Integer, primary_key=True)
    quantityordered = Column(Integer)
    priceeach = Column(Float)
    orderlinenumber = Column(Integer)
    sales = Column(Float)
    orderdate = Column(DateTime)
    status = Column(String)
    qtr_id = Column(Integer)
    month_id = Column(Integer)
    year_id = Column(Integer)
    productline = Column(String)
    msrp = Column(Float)
    productcode = Column(String)
    customername = Column(String)
    phone = Column(String)
    addressline1 = Column(String)
    addressline2 = Column(String)
    city = Column(String)
    state = Column(String)
    postalcode = Column(String)
    country = Column(String)
    territory = Column(String)
    contactlastname = Column(String)
    contactfirstname = Column(String)
    dealsize = Column(String)


class CleanData(Base): 
    __tablename__ = "clean_data"  

    ORDERNUMBER = Column(Integer, primary_key=True) 
    QUANTITYORDERED = Column(Integer)
    PRICEEACH = Column(Float)
    ORDERLINENUMBER = Column(Integer)
    SALES = Column(Float)
    ORDERDATE = Column(DateTime)
    STATUS = Column(String)
    QTR_ID = Column(Integer)
    MONTH_ID = Column(Integer)
    YEAR_ID = Column(Integer)
    PRODUCTLINE = Column(String)
    MSRP = Column(Float)
    PRODUCTCODE = Column(String)
    CUSTOMERNAME = Column(String)
    PHONE = Column(String)
    ADDRESSLINE1 = Column(String)
    ADDRESSLINE2 = Column(String)
    CITY = Column(String)
    STATE = Column(String)
    POSTALCODE = Column(String)
    COUNTRY = Column(String)
    TERRITORY = Column(String)
    CONTACTLASTNAME = Column(String)
    CONTACTFIRSTNAME = Column(String)
    DEALSIZE = Column(String)


class FaultyData(Base): 
    __tablename__ = "faulty_data"  

    id = Column(Integer, primary_key=True, autoincrement=True)
    ORDERNUMBER = Column(Integer) 
    QUANTITYORDERED = Column(Integer)
    PRICEEACH = Column(Float)
    ORDERLINENUMBER = Column(Integer)
    SALES = Column(Float)
    ORDERDATE = Column(DateTime)
    STATUS = Column(String)
    QTR_ID = Column(Integer)
    MONTH_ID = Column(Integer)
    YEAR_ID = Column(Integer)
    PRODUCTLINE = Column(String)
    MSRP = Column(Float)
    PRODUCTCODE = Column(String)
    CUSTOMERNAME = Column(String)
    PHONE = Column(String)
    ADDRESSLINE1 = Column(String)
    ADDRESSLINE2 = Column(String)
    CITY = Column(String)
    STATE = Column(String)
    POSTALCODE = Column(String)
    COUNTRY = Column(String)
    TERRITORY = Column(String)
    CONTACTLASTNAME = Column(String)
    CONTACTFIRSTNAME = Column(String)
    DEALSIZE = Column(String)
    VALIDATION_ERRORS = Column(String)